name: CI/CD for PlatformIO

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  platformio-build-esp32dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        pip install platformio
        platformio update

    - name: Build PlatformIO Project for ESP32
      run: platformio run -e esp32dev

    - name: Build fs image
      run: pio run -t buildfs -e esp32dev

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: platformio-build-esp32dev
        path: .pio/build

    - name: Cleanup
      run: rm -rf .pio

  platformio-build-esp8266:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        pip install platformio
        platformio update

    - name: Build PlatformIO Project for ESP8266
      run: platformio run -e esp8266

    - name: Build fs image
      run: pio run -t buildfs -e esp8266

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: platformio-build-esp8266
        path: .pio/build

    - name: Cleanup
      run: rm -rf .pio